### PR TITLE
feat: add function `extractMetaboliteGSN`

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
### Main improvements in this PR:

- Add a new function `extractMetaboliteGSN` that can be used to extract metabolite gene set-gene set interaction file from a GEM
- The extracted gene set interaction file can be used as one input for the [Kiwi](https://github.com/SysBioChalmers/Kiwi) network analysis

### CODE REVIEW

**Review by JonathanRob — APPROVED** [review]
@haowang-bioinfo sorry for the super long delay on this, I kept forgetting to address this.

I made some adjustments to your `extractMetaboliteGSN` function:

First, it seems that metabolites were only counted as interacting if they appeared on opposite sides of a reaction (i.e., one was a substrate, the other a product), while I think they should be counted as interacting even if they are both substrates or both products in the same reaction.

Next, I removed duplicate interactions, and self-interactions, which greatly reduces the file size. I couldn't tell whether Kiwi uses the number of interactions as a metric; if so, then we should modify this function so that the user can choose whether to remove duplicate interactions or to keep them.

**Comment by haowang-bioinfo** [comment]
> I made some adjustments to your extractMetaboliteGSN function

thanks for the input

this `extractMetaboiteGSN` was drafted according to the [tutorial](https://pythonhosted.org/KiwiDist/tutorial.html) of Kiwi, which counts the number of interaction for plotting edge width - the thicker the more interactions. It probably is better to keep this option so as to be compatible with Kiwi.

**Comment by JonathanRob** [comment]
Ok, in that case I will adjust so it keeps the duplicate interactions by default, but can be optionally removed.

**Comment by JonathanRob** [comment]
Ok @haowang-bioinfo, I revised the function so that by default it will not remove duplicate geneset-geneset interactions, but the user has the option to do so.

**Comment by haowang-bioinfo** [comment]
lgtm, go ahead please

**Pull request merged**
